const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const Routine = sequelize.define('Routine', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: 'user_id',
      references: {
        model: 'users',
        key: 'id'
      }
    },
    weekStart: {
      type: DataTypes.DATEONLY,
      allowNull: false,
      field: 'week_start'
    },
    plan: {
      type: DataTypes.JSONB,
      allowNull: true,
      comment: 'Weekly workout plan generated by AI'
    },
    progress: {
      type: DataTypes.JSONB,
      allowNull: true,
      defaultValue: {},
      comment: 'Completed exercises tracking'
    },
    isActive: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
      field: 'is_active'
    }
  }, {
    tableName: 'routines',
    timestamps: true,
    createdAt: 'created_at',
    updatedAt: 'updated_at'
  });

  return Routine;
};
